version: '3.8'

services:
  redis:
    container_name: redis
    image: redis
    restart: always

  web:
    container_name: django
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: zxcvbnm8
      POSTGRES_DB: dz11_annotate_aggregate
      POSTGRES_USER: postgres_admin
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-alpine
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celeryworker:
    container_name: celeryworker
    build: .
    env_file:
      - .env
    volumes:
      - ./:/web
    command: celery -A dz11_annotate_aggregate worker -l info
    depends_on:
      - rabbitmq

  celeryscheduler:
    container_name: celeryscheduler
    build: .
    env_file:
      - .env
    volumes:
      - ./:/web
    command: celery -A dz11_annotate_aggregate beat -l info
    depends_on:
      - rabbitmq


volumes:
  data_postgres:
  rabbitmq_data: