version: '3.8'

services:
  redis:
    image: redis
    restart: always

  web:
    container_name: django
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env


  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: zxcvbnm8
      POSTGRES_DB: dz11_annotate_aggregate
      POSTGRES_USER: postgres_admin
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data_postgres: